### ISSUE TITLE
maven: mvn package generates broken JAR-with-dependencies

### ISSUE THREAD

**Issue by llongi** [inilabs/caerctl-gui-javafx#5]
The jar-with-dependencies generated by Maven does not work since the ikonli icons system is in use.
Exception is:

```
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Cannot resolve 'fa-chain'
	at org.kordamp.ikonli.javafx.IkonResolver.resolveIkonHandler(IkonResolver.java:60)
	at org.kordamp.ikonli.javafx.FontIcon.setIconCode(FontIcon.java:215)
	at org.kordamp.ikonli.javafx.FontIcon$8.changed(FontIcon.java:174)
	at org.kordamp.ikonli.javafx.FontIcon$8.changed(FontIcon.java:171)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.ObjectPropertyBase.fireValueChangedEvent(ObjectPropertyBase.java:105)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:112)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.css.StyleableObjectProperty.set(StyleableObjectProperty.java:82)
	at org.kordamp.ikonli.javafx.FontIcon.setIconCode(FontIcon.java:214)
	at org.kordamp.ikonli.javafx.FontIcon.<init>(FontIcon.java:86)
	at com.inilabs.caerControlGuiJavaFX.generateConnectGUI(caerControlGuiJavaFX.java:117)
	at com.inilabs.caerControlGuiJavaFX.start(caerControlGuiJavaFX.java:75)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:748)
Exception in Application start method
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$1(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsupportedOperationException: Cannot resolve 'fa-chain'
	at org.kordamp.ikonli.javafx.IkonResolver.resolveIkonHandler(IkonResolver.java:60)
	at org.kordamp.ikonli.javafx.FontIcon.setIconCode(FontIcon.java:215)
	at org.kordamp.ikonli.javafx.FontIcon.<init>(FontIcon.java:86)
	at com.inilabs.caerControlGuiJavaFX.generateConnectGUI(caerControlGuiJavaFX.java:117)
	at com.inilabs.caerControlGuiJavaFX.start(caerControlGuiJavaFX.java:75)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$8(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$7(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$5(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$6(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$5(GtkApplication.java:139)
	... 1 more
Exception running application com.inilabs.caerControlGuiJavaFX
```

Generating the JAR with Eclipse->Export works, but fails to find the CSS style-sheet then.

**Comment by llongi** [comment]
Fixed in 0c84f9918e061d6f2f611b5d98a905821a773a54 by changing to use ControlsFX FontAwesome support, which is already included.
